# Generated by Django 4.1.1 on 2022-09-30 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_category_options_alter_post_catrgory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catrgory',
            new_name='category',
        ),
    ]
